#!/usr/bin/env bash
set -euo pipefail

# ─── Hermes Agent Discord Gateway Launcher ───
# One-script startup for the Hermes AI Discord bot.
# Uses the conda hermes-agent environment (Python 3.13).
# Runs with HERMES_HOME set to the local hermas/.hermes directory.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# ─── Local Hermes Home Configuration ───
# Use local hermas/.hermes instead of ~/.hermes
export HERMES_HOME="$SCRIPT_DIR/.hermes"
HERMES_ENV="$HERMES_HOME/.env"
HERMES_CONFIG="$HERMES_HOME/config.yaml"

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ─── Activate Conda Environment ───
CONDA_BASE="${CONDA_BASE:-$HOME/miniconda3}"
if [ ! -f "$CONDA_BASE/bin/conda" ]; then
    error "Miniconda not found at $CONDA_BASE. Set CONDA_BASE env var."
fi

info "Activating conda environment: hermes-agent"
# Source conda.sh directly for reliable activation in bash scripts
source "$CONDA_BASE/etc/profile.d/conda.sh"
conda activate hermes-agent || error "Failed to activate hermes-agent conda env"

# Ensure conda env Python takes priority over system Python
export PATH="$CONDA_PREFIX/bin:$PATH"

info "Python: $(python --version)"
info "HERMES_HOME: $HERMES_HOME"

# ─── Ensure Discord dependencies are installed ───
if ! python -c "import discord" 2>/dev/null; then
    info "Installing Discord messaging dependencies..."
    pip install -q "discord.py[voice]>=2.7.1,<3" "aiohttp>=3.13.3,<4" 2>&1
fi

# ─── Ensure Local Hermes Directory Structure ───
if [ ! -d "$HERMES_HOME" ]; then
    info "Creating local HERMES_HOME directory: $HERMES_HOME"
    mkdir -p "$HERMES_HOME"
fi

# ─── Sync Discord Token ───
# Pull Discord bot token from OpenClaw config
OPENCLAW_CONFIG="$PROJECT_ROOT/openclaw.json"
DISCORD_TOKEN=""

if [ -f "$OPENCLAW_CONFIG" ]; then
    # Extract Discord token from openclaw.json using python
    DISCORD_TOKEN=$(python -c "
import json, sys
try:
    with open('$OPENCLAW_CONFIG') as f:
        cfg = json.load(f)
    token = cfg.get('channels', {}).get('discord', {}).get('token', '')
    if token:
        print(token)
except Exception as e:
    print('', file=sys.stderr)
" 2>/dev/null)

    if [ -n "$DISCORD_TOKEN" ]; then
        info "Found Discord token in openclaw.json"
    else
        warn "No Discord token found in openclaw.json"
    fi
else
    warn "openclaw.json not found at $OPENCLAW_CONFIG"
fi

# ─── Sync OpenRouter API Key ───
PROJECT_ENV="$PROJECT_ROOT/.env"
if [ -f "$PROJECT_ENV" ] && grep -q "^OPENROUTER_API_KEY=" "$PROJECT_ENV" 2>/dev/null; then
    OPENROUTER_KEY=$(grep "^OPENROUTER_API_KEY=" "$PROJECT_ENV" | cut -d'=' -f2-)
    if [ -n "$OPENROUTER_KEY" ]; then
        export OPENROUTER_API_KEY="$OPENROUTER_KEY"
        info "Loaded OPENROUTER_API_KEY from project .env"
        # Also sync into hermes .env so Hermes can read it at runtime
        if [ -f "$HERMES_ENV" ]; then
            if grep -q "^OPENROUTER_API_KEY=" "$HERMES_ENV" 2>/dev/null; then
                sed -i '' "s|^OPENROUTER_API_KEY=.*|OPENROUTER_API_KEY=$OPENROUTER_KEY|" "$HERMES_ENV"
            else
                echo "" >> "$HERMES_ENV"
                echo "# OpenRouter API key" >> "$HERMES_ENV"
                echo "OPENROUTER_API_KEY=$OPENROUTER_KEY" >> "$HERMES_ENV"
            fi
            info "Synced OPENROUTER_API_KEY to $HERMES_ENV"
        fi
    fi
fi

# ─── Setup .env file ───
if [ -n "$DISCORD_TOKEN" ]; then
    if [ -f "$HERMES_ENV" ]; then
        if grep -q "^DISCORD_BOT_TOKEN=" "$HERMES_ENV" 2>/dev/null; then
            info "DISCORD_BOT_TOKEN already set in $HERMES_ENV"
        else
            info "Adding DISCORD_BOT_TOKEN to $HERMES_ENV"
            echo "" >> "$HERMES_ENV"
            echo "# Discord bot token (synced from openclaw.json)" >> "$HERMES_ENV"
            echo "DISCORD_BOT_TOKEN=$DISCORD_TOKEN" >> "$HERMES_ENV"
        fi
    else
        info "Creating $HERMES_ENV with Discord token"
        echo "# Hermes environment configuration" > "$HERMES_ENV"
        echo "# Auto-generated by start-hermes.sh" >> "$HERMES_ENV"
        echo "" >> "$HERMES_ENV"
        echo "# Discord bot token (synced from openclaw.json)" >> "$HERMES_ENV"
        echo "DISCORD_BOT_TOKEN=$DISCORD_TOKEN" >> "$HERMES_ENV"
    fi
    export DISCORD_BOT_TOKEN="$DISCORD_TOKEN"
fi

# ─── Verify Discord Token ───
if [ -z "${DISCORD_BOT_TOKEN:-}" ]; then
    # Try loading from local hermes .env
    if [ -f "$HERMES_ENV" ] && grep -q "^DISCORD_BOT_TOKEN=" "$HERMES_ENV"; then
        export DISCORD_BOT_TOKEN=$(grep "^DISCORD_BOT_TOKEN=" "$HERMES_ENV" | cut -d'=' -f2-)
    fi
fi

if [ -z "${DISCORD_BOT_TOKEN:-}" ]; then
    error "No DISCORD_BOT_TOKEN found. Set it in $HERMES_ENV or openclaw.json"
fi

info "Discord bot token: ${DISCORD_BOT_TOKEN:0:10}...${DISCORD_BOT_TOKEN: -4}"

# ─── Check/Create config.yaml ───
if [ ! -f "$HERMES_CONFIG" ]; then
    info "Creating minimal config.yaml at $HERMES_CONFIG"
    cat > "$HERMES_CONFIG" << 'EOF'
# Hermes configuration for Discord gateway
# Auto-generated by start-hermes.sh

platforms:
  discord:
    enabled: true

discord:
  require_mention: false
EOF
fi

# ─── Start Gateway ───
info "Starting Hermes Discord gateway..."
info "Press Ctrl+C to stop"
echo ""

exec hermes gateway run -v "$@"
